# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://evgen.zhlobo.info
title: Блог Евгения Жлобо
author: Евгений Жлобо
simple_search: http://google.com/search

# Default date format is "ordinal" (resulting in "July 22nd 2007")
# You can customize the format as defined in
# http://www.ruby-doc.org/core-1.9.2/Time.html#method-i-strftime
# Additionally, %o will give you the ordinal representation of the day
date_format: "%d %B в %H:%M"

# RSS / Email (optional) subscription links (change if using something like Feedburner)
subscribe_rss: /atom.xml
subscribe_email:
# RSS feeds can list your email address if you like
email: evgen.zhlobo@gmail.com

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# If publishing to a subdirectory as in http://site.com/project set 'root: /project'
root: /
permalink: /blog/:title/
source: source
destination: public
plugins: plugins
code_dir: downloads/code
category_dir: blog/categories
markdown: rdiscount
pygments: false       # default python pygments have been replaced by pygments.rb

paginate: 10          # Posts per page on the blog index
pagination_dir: blog  # Directory base for pagination URLs eg. /blog/page/2/
excerpt_link: "<span>Читать далее</span> &rarr;" # "Continue reading" link text at the bottom of excerpted articles

titlecase: true       # Converts page and post titles to titlecase
